# Generated by Django 5.2.8 on 2025-11-22 16:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('director', models.CharField(blank=True, max_length=100)),
                ('genre', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('sci-fi', 'Sci-Fi'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('documentary', 'Documentary'), ('animation', 'Animation'), ('fantasy', 'Fantasy'), ('crime', 'Crime'), ('adventure', 'Adventure')], max_length=50)),
                ('platform', models.CharField(choices=[('netflix', 'Netflix'), ('prime', 'Prime Video'), ('disney', 'Disney+'), ('hulu', 'Hulu'), ('hbo', 'HBO Max'), ('apple', 'Apple TV+'), ('paramount', 'Paramount+'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('completed', 'Completed'), ('wishlist', 'Wishlist')], default='wishlist', max_length=20)),
                ('content_type', models.CharField(choices=[('movie', 'Movie'), ('tv_show', 'TV Show')], max_length=20)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.content')),
                ('duration', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
            bases=('api.content',),
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.content')),
                ('total_seasons', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_episodes', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('seasons_watched', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('episodes_watched', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('average_episode_duration', models.IntegerField(default=45, help_text='Duration in minutes')),
            ],
            options={
                'verbose_name': 'TV Show',
                'verbose_name_plural': 'TV Shows',
            },
            bases=('api.content',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('review_text', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about the content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.content')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_watched', models.DateTimeField(auto_now_add=True)),
                ('watch_duration', models.IntegerField(blank=True, help_text='Duration watched in minutes', null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='api.content')),
            ],
            options={
                'verbose_name_plural': 'Watch History',
                'ordering': ['-date_watched'],
            },
        ),
    ]
